### ISSUE TITLE
Pls Review your Documentation

### ISSUE THREAD

**Issue by lucasdozie** [zvook/php-skrill-quick-checkout#1]
Please Review your documentation, some lines there are kind of misleading.
I got an error message "class doesn't exist" myself when I first ran it, it was later after going through each class that I discover the typo
e.g
change 
use zvook\Skrill\Models\QuickCheckoutForm;
to
use zvook\Skrill\Forms\QuickCheckoutForm;

**Comment by xaerobiont** [comment]
@lucasdozie sorry for 1.5 years delay :) Thanks, doc fixed
