### ISSUE TITLE
How to handle error payment

### ISSUE THREAD

**Issue by phamngocson1988** [zvook/php-skrill-quick-checkout#3]
When I verify the request sent back from Skrill (POST via status_url), I process something in my website and return a header 200, Skrill also confirms that "payment success" and return back to the website. But Skill keep sending confirm request many times (via status_url)

Another problem I get from Skill is when I receive params from status_url and process on my website, I throw an error (because there is something wrong on my system, for example), but why Skrill still says "Payment success"

I'm not really understand this point. Could you please give me some ideas?

**Comment by xaerobiont** [comment]
Did you solve it?
